# Generated by Django 4.1.3 on 2022-11-05 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_postedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 19, 36, 13, 846420, tzinfo=datetime.timezone.utc)),
        ),
    ]
